bitbucket-helper {
  http {
    host = "127.0.0.1"
    port = 8080
  }
  database.path = "./var/bitbucket-helper.sqlite"
  refresh.interval = "PT15M"
  bitbucket {
    base-url = "https://api.bitbucket.org/2.0"
    request-timeout = "PT30S"
  }
}
