bitbucket-helper {
  http {
    host = "127.0.0.1"
    port = 8080
  }
  database.path = "./var/bitbucket-helper.sqlite"
  unix-socket.path = "./var/bitbucket-helper.sock"
  notification.executable = "/usr/local/bin/desktop-notifications"
  bitbucket {
    request-timeout = "PT30S"
  }
}
